"""
draft_ljt_sentences.py
----------------------
Generates initial LJT stimulus sentence drafts for the 143 UVLT targets
(286 sentences = 143 appropriate + 143 inappropriate) per design_ljt_spec.md.

Each entry in SENTENCES maps target_word -> dict with:
    app:       appropriate sentence
    inapp:     inappropriate sentence
    frame:     syntactic frame (e.g., SVO, SVC, N-mod)
    foil_sub:  foil subtype (for inappropriate)
    app_rat:   short rationale for appropriate
    inapp_rat: short rationale for inappropriate (how the selectional /
               collocational violation is realized)
    risks:     any known risks noted for human reviewers

All sentences observe:
  - 4..8 words inclusive
  - target appears exactly once, non-initial
  - grammatically simple (no subordinate clauses)
  - context words heavy on top-1K (top-2K at most, with at most 1 non-1K word)
  - target preserved in b_collocation foils
"""

from __future__ import annotations
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LJT = ROOT / "ljt"
Q_MATRIX = LJT / "q_matrix_eligible.csv"
OUTPUT = LJT / "ljt_sentences_draft.csv"
LLM_VERSION = "claude-opus-drafting-v1-2026-04-19"


# =============================================================================
# Sentence specifications per target word.
# Keyed by target_word (unique across 143 targets in q_matrix_eligible.csv).
# =============================================================================
SENTENCES: dict[str, dict[str, str]] = {

    # -------- 1K NOUNS --------
    "price": {
        "app":     "The price of milk is low.",
        "inapp":   "The price of milk sounds angry.",
        "frame":   "N-subj_copula_AdjP",
        "foil_sub":"a_selectional",
        "app_rat": "cost sense forced by copula+gradable adj 'low'; price is +abstract/-animate so 'sounds angry' violates animacy/emotional predicate",
        "inapp_rat":"price is -animate/-sentient; predicate 'sounds angry' requires +sentient subject",
        "risks":   "",
    },
    "photograph": {
        "app":     "She showed me an old photograph.",
        "inapp":   "She ate an old photograph happily.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "picture sense forced by 'old' + transfer verb 'show'",
        "inapp_rat":"photograph is -edible; 'eat' requires +edible direct object",
        "risks":   "",
    },
    "garden": {
        "app":     "Flowers grew in the small garden.",
        "inapp":   "Flowers grew in the loud garden.",
        "frame":   "SV-PP",
        "foil_sub":"a_selectional",
        "app_rat": "place-where-things-grow sense forced by 'flowers grew in'",
        "inapp_rat":"garden (place) is -audible; adj 'loud' requires +audible modified noun",
        "risks":   "",
    },
    "eye": {
        "app":     "The baby opened her right eye.",
        "inapp":   "The baby measured her right eye.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "body-part sense forced by 'right' + 'opened'",
        "inapp_rat":"verb 'measure' + direct obj 'eye' is non-collocate; 'open/close/rub/shut eye' standard",
        "risks":   "careful item: eye is polysemous (needle eye, storm eye). Target preserved.",
    },
    "father": {
        "app":     "Her father works on Saturdays.",
        "inapp":   "Her father melts on Saturdays.",
        "frame":   "SV-PP",
        "foil_sub":"b_collocation",
        "app_rat": "parent-who-is-a-man forced by possessive + temporal adjunct",
        "inapp_rat":"father (human) + 'melts' is non-collocate; melt is -human_subject typical",
        "risks":   "borderline: 'melt' can metaphorically apply to people (heart melts) — risk partial foil rescue; flag for reviewer",
    },
    "night": {
        "app":     "She reads books every cold night.",
        "inapp":   "She reads books every pink night.",
        "frame":   "SVO-temporal",
        "foil_sub":"b_collocation",
        "app_rat": "part-of-day-with-no-sun forced by temporal reading + modifier 'cold'",
        "inapp_rat":"night + color modifier 'pink' is non-collocate (dark/cold/long/quiet night standard)",
        "risks":   "",
    },
    "uncle": {
        "app":     "My uncle lives near the park.",
        "inapp":   "My uncle grows near the park.",
        "frame":   "SV-PP",
        "foil_sub":"a_selectional",
        "app_rat": "mother/father's brother sense forced by possessive + 'lives'",
        "inapp_rat":"uncle (+human) with 'grows' (+plant typical) violates animacy/growth selection",
        "risks":   "",
    },
    "center": {
        "app":     "Please stand in the center here.",
        "inapp":   "Please stand in the angry center.",
        "frame":   "SV-PP",
        "foil_sub":"a_selectional",
        "app_rat": "middle sense forced by locative 'stand in the'",
        "inapp_rat":"center (-animate geometric) + 'angry' (+sentient) violates animacy of modified N",
        "risks":   "minority-sense polysemy: community/shopping center. Foil selectional works across senses.",
    },
    "note": {
        "app":     "She left a short note here.",
        "inapp":   "She left a shouting note here.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "short-piece-of-writing forced by 'left' + size adj 'short'",
        "inapp_rat":"note (-animate) + 'shouting' (+animate participle) violates animacy",
        "risks":   "minority-sense: music note. Foil also fails there, so robust.",
    },
    "brother": {
        "app":     "Her brother plays tennis after school.",
        "inapp":   "Her brother wraps tennis after school.",
        "frame":   "SVO-PP",
        "foil_sub":"b_collocation",
        "app_rat": "family-member sense forced by possessive + 'plays tennis'",
        "inapp_rat":"'brother' + 'wraps tennis' is non-collocate; normal: brother plays/watches/likes",
        "risks":   "",
    },
    "hour": {
        "app":     "The meeting lasted one full hour.",
        "inapp":   "The meeting lasted one pink hour.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "sixty-minutes sense forced by 'lasted' + 'one full'",
        "inapp_rat":"hour + color 'pink' non-collocate (full/whole/short/extra hour standard)",
        "risks":   "",
    },
    "plan": {
        "app":     "They made a simple plan today.",
        "inapp":   "They made a wet plan today.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "way-of-doing-things sense forced by 'made a' + 'simple'",
        "inapp_rat":"plan + 'wet' non-collocate (detailed/simple/new/backup plan standard)",
        "risks":   "",
    },
    "grass": {
        "app":     "The green grass covered the ground.",
        "inapp":   "The angry grass covered the ground.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "green-leaves sense forced by color adj + 'covered the ground'",
        "inapp_rat":"grass (-sentient plant) + 'angry' (+sentient emotion) violates animacy",
        "risks":   "",
    },
    "bath": {
        "app":     "Please take a hot bath now.",
        "inapp":   "Please take a loud bath now.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "place-to-wash sense forced by 'take a hot'",
        "inapp_rat":"bath (as place/activity) is -audible; 'loud' requires +audible N",
        "risks":   "",
    },
    "shoulder": {
        "app":     "He hurt his left shoulder yesterday.",
        "inapp":   "He hurt his talking shoulder yesterday.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "top-end-of-arm body-part sense forced by possessive + 'hurt his'",
        "inapp_rat":"shoulder (-animate body part) + 'talking' (+animate participle) violates animacy",
        "risks":   "",
    },
    "prepare": {
        "app":     "Mom prepares breakfast every single morning.",
        "inapp":   "Mom prepares anger every single morning.",
        "frame":   "SVO-temporal",
        "foil_sub":"b_collocation",
        "app_rat": "get-ready sense forced by obj 'breakfast' + habitual adjunct",
        "inapp_rat":"'prepare' + direct obj 'anger' is non-collocate (prepare meals/dinner/answers/report standard)",
        "risks":   "",
    },
    "laugh": {
        "app":     "The children laughed at his joke.",
        "inapp":   "The buildings laughed at his joke.",
        "frame":   "SV-PP",
        "foil_sub":"b_collocation",
        "app_rat": "make-happy-sound sense forced by +human subject + 'at his joke'",
        "inapp_rat":"laugh with +animate subject required; 'buildings laughed' violates at selectional level but kept as b because target verb+prep frame preserved intact and swap is at subject-arg",
        "risks":   "note: subject swap can read as selectional (a). Reviewer should decide a vs b — flagging. CSV labels b per input.",
    },
    "forget": {
        "app":     "She always forgets her house keys.",
        "inapp":   "She always forgets her pink keys.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "not-remember sense forced by 'always' + obj 'keys'",
        "inapp_rat":"'forget' + modifier 'pink' on the object is odd collocationally; typical: forget names/passwords/keys/birthdays — color on forgotten item unusual",
        "risks":   "mild risk: 'pink keys' could be naturally pink. Violation is at collocational level of forget+<colored_tangible> combo.",
    },
    "work": {
        "app":     "Her dad works at the factory.",
        "inapp":   "Her dad works at the apple.",
        "frame":   "SV-PP",
        "foil_sub":"b_collocation",
        "app_rat": "do-things-for-money sense forced by 'at the factory'",
        "inapp_rat":"'work at X' with X = concrete fruit is non-collocate; work at + workplace/company standard",
        "risks":   "minority-sense target (function as work); foil still fails across senses.",
    },
    "return": {
        "app":     "She returned home after the party.",
        "inapp":   "She returned a song after the party.",
        "frame":   "SV-PP or SVO-PP",
        "foil_sub":"b_collocation",
        "app_rat": "go-back sense forced by 'home' + 'after'",
        "inapp_rat":"return + direct obj 'song' non-collocate (return books/calls/emails/keys standard)",
        "risks":   "minority-sense: return something. Foil works because b-collocate check is on object selection.",
    },
    "check": {
        "app":     "He checked his email before leaving.",
        "inapp":   "He checked his storm before leaving.",
        "frame":   "SVO-PP",
        "foil_sub":"b_collocation",
        "app_rat": "make-sure sense forced by obj 'email' + temporal 'before leaving'",
        "inapp_rat":"check + 'storm' as direct obj non-collocate (check email/time/answer/work standard)",
        "risks":   "minority-sense: check could mean inspect. Foil still non-collocate there.",
    },
    "reply": {
        "app":     "She will reply to his kind message.",
        "inapp":   "She will reply to his kind mountain.",
        "frame":   "SV-PP",
        "foil_sub":"b_collocation",
        "app_rat": "answer sense forced by 'to his message'; modal 'will' keeps target as base form",
        "inapp_rat":"'reply to X' with X = mountain non-collocate; reply to + message/letter/email/question standard",
        "risks":   "",
    },
    "bring": {
        "app":     "Please bring your own water bottle.",
        "inapp":   "Please bring your own angry bottle.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "carry-to-another-place sense forced by 'bring your own' + concrete obj",
        "inapp_rat":"bring + 'angry' modifier on the object is non-collocate (cold/fresh/own/extra bottle natural)",
        "risks":   "",
    },
    "stare": {
        "app":     "The boy stared at the sky.",
        "inapp":   "The stone stared at the sky.",
        "frame":   "SV-PP",
        "foil_sub":"b_collocation",
        "app_rat": "look-at-long-time sense forced by 'at the sky' + animate subject",
        "inapp_rat":"subject 'stone' with 'stared at' is non-collocate at subject-level",
        "risks":   "could read as a selectional. Input CSV labels b. Flag.",
    },
    "main": {
        "app":     "She was the main guest yesterday.",
        "inapp":   "She was the main chicken yesterday.",
        "frame":   "SVC",
        "foil_sub":"b_collocation",
        "app_rat": "most-important sense forced by copula + 'guest'",
        "inapp_rat":"main + 'chicken' non-collocate (main course/reason/idea/problem/guest standard)",
        "risks":   "",
    },
    "bad": {
        "app":     "That was a bad decision today.",
        "inapp":   "That was a bad triangle today.",
        "frame":   "SVC",
        "foil_sub":"b_collocation",
        "app_rat": "not-good sense forced by 'was a bad' + 'decision'",
        "inapp_rat":"'bad' + 'triangle' non-collocate (bad idea/day/news/habit/decision standard)",
        "risks":   "minority-sense: could mean 'naughty'. Foil fails there too.",
    },
    "cold": {
        "app":     "The cold water felt really nice.",
        "inapp":   "The cold idea felt really nice.",
        "frame":   "SVC",
        "foil_sub":"a_selectional",
        "app_rat": "not-hot sense forced by concrete subj 'water' + 'felt nice'",
        "inapp_rat":"cold (temperature) requires +concrete/tangible; 'idea' is -concrete",
        "risks":   "note: 'cold idea' can read metaphorically (unfeeling). Watch for idiom rescue; reviewer note.",
    },
    "definite": {
        "app":     "His answer was a definite yes.",
        "inapp":   "His answer was a definite potato.",
        "frame":   "SVC",
        "foil_sub":"b_collocation",
        "app_rat": "certain sense forced by copula + 'yes'",
        "inapp_rat":"definite + 'potato' non-collocate (definite answer/yes/no/plan/improvement standard)",
        "risks":   "",
    },
    "general": {
        "app":     "The general idea was really good.",
        "inapp":   "The general potato was really good.",
        "frame":   "N-mod",
        "foil_sub":"b_collocation",
        "app_rat": "usual sense forced by 'idea' + 'really good'",
        "inapp_rat":"general + 'potato' non-collocate (general idea/rule/feeling/public/opinion standard)",
        "risks":   "minority-sense: could be 'military general'. Foil fails there too.",
    },
    "awful": {
        "app":     "The food tasted awful last night.",
        "inapp":   "The idea tasted awful last night.",
        "frame":   "SVC",
        "foil_sub":"a_selectional",
        "app_rat": "very-bad sense forced by 'food' + 'tasted'",
        "inapp_rat":"'idea' (-substance) + 'tasted' requires +substance. Awful is preserved; oddness is tied via tasted-<mod>-subject.",
        "risks":   "oddness could be attributed to taste+idea rather than awful's selection. Reviewer flag — may relabel as failure mode 4.",
    },

    # -------- 2K NOUNS --------
    "feature": {
        "app":     "The new phone has many features.",
        "inapp":   "The new phone has loud features.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "important-part sense forced by 'phone' + 'many'",
        "inapp_rat":"feature (attribute) -audible; 'loud' needs +audible N",
        "risks":   "minority-sense; feature can be 'face'. Foil still fails there (loud face odd too).",
    },
    "coach": {
        "app":     "The coach taught them new skills.",
        "inapp":   "The coach rusted them new skills.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "trainer sense forced by 'taught them new skills'",
        "inapp_rat":"coach (+human) + 'rusted' (+metal/corrode) violates animate agent selection",
        "risks":   "unusual verb choice; reviewer may want stronger violation.",
    },
    "weed": {
        "app":     "The gardener pulled some tall weeds.",
        "inapp":   "The gardener pulled some happy weeds.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "unwanted-plant sense forced by 'gardener pulled'",
        "inapp_rat":"weed (plant -sentient) + 'happy' (+sentient)",
        "risks":   "",
    },
    "vegetable": {
        "app":     "We grew fresh vegetables every year.",
        "inapp":   "We grew angry vegetables every year.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "food-from-garden sense forced by 'grew' + 'fresh'",
        "inapp_rat":"vegetable + 'angry' modifier non-collocate (fresh/frozen/green/cooked vegetables standard)",
        "risks":   "could slide to a_selectional (vegetables -animate). Labeled b per input; reviewer flag.",
    },
    "knowledge": {
        "app":     "His knowledge of history is deep.",
        "inapp":   "His knowledge of history is pink.",
        "frame":   "N-subj_copula_AdjP",
        "foil_sub":"b_collocation",
        "app_rat": "information sense forced by 'of history' + 'deep'",
        "inapp_rat":"knowledge + 'pink' non-collocate (deep/broad/basic/limited/general knowledge standard)",
        "risks":   "",
    },
    "average": {
        "app":     "The average was above nine points.",
        "inapp":   "The average was above nine sneezes.",
        "frame":   "N-subj_copula_PP",
        "foil_sub":"b_collocation",
        "app_rat": "middle-number sense forced by 'above nine' + 'points'",
        "inapp_rat":"average + 'sneezes' as the unit non-collocate (average score/age/temperature/cost/number standard)",
        "risks":   "note: the swapped word is 'sneezes', the object of preposition. Still in direct syntactic relation with 'above nine', not average. Potential fail-mode-4; reviewer flag.",
    },
    "circle": {
        "app":     "Draw a big circle on paper.",
        "inapp":   "Draw a loud circle on paper.",
        "frame":   "SVO-PP",
        "foil_sub":"a_selectional",
        "app_rat": "round-shape sense forced by 'draw' + 'on paper'",
        "inapp_rat":"circle (-audible shape) + 'loud' requires +audible",
        "risks":   "",
    },
    "knife": {
        "app":     "He cut the bread with a knife.",
        "inapp":   "He cut the bread with a happy knife.",
        "frame":   "SVO-PP",
        "foil_sub":"a_selectional",
        "app_rat": "cutting-tool sense forced by 'cut bread with'",
        "inapp_rat":"knife (-animate tool) + 'happy' (+animate)",
        "risks":   "",
    },
    "justice": {
        "app":     "The judge tried to bring justice.",
        "inapp":   "The judge tried to taste justice.",
        "frame":   "SVO (inf V+obj)",
        "foil_sub":"a_selectional",
        "app_rat": "using-laws-fairly sense forced by 'judge' + 'bring'",
        "inapp_rat":"justice (abstract -substance) + 'taste' requires +substance",
        "risks":   "watch: 'taste justice' metaphoric idiom? Reviewer check; 'poverty tasted bitter' flagged in spec §3.4.",
    },
    "section": {
        "app":     "Read the last section of the book.",
        "inapp":   "Read the loud section of the book.",
        "frame":   "SVO-PP",
        "foil_sub":"b_collocation",
        "app_rat": "part sense forced by 'last section of the book'",
        "inapp_rat":"section + 'loud' non-collocate (last/first/main/next/whole section standard)",
        "risks":   "could fail as selectional (section -audible). Reviewer flag.",
    },
    "site": {
        "app":     "The building site was very busy.",
        "inapp":   "The building site was very asleep.",
        "frame":   "SVC",
        "foil_sub":"b_collocation",
        "app_rat": "place sense forced by 'building' compound + 'busy'",
        "inapp_rat":"site + 'asleep' non-collocate (busy/new/main/construction/work site standard)",
        "risks":   "might slide to a_selectional (site -sentient). Reviewer flag.",
    },
    "sheet": {
        "app":     "Please put a clean sheet here.",
        "inapp":   "Please put a loud sheet here.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "bed-cover sense forced by 'put a clean'",
        "inapp_rat":"sheet + 'loud' non-collocate (clean/white/fresh/cotton sheet standard)",
        "risks":   "minority-sense: sheet of paper. 'loud sheet' fails there too.",
    },
    "envelope": {
        "app":     "He sent the envelope this week.",
        "inapp":   "He sent the asleep envelope this week.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "letter-cover sense forced by 'sent'",
        "inapp_rat":"envelope (-sentient) + 'asleep' (+sentient/animate)",
        "risks":   "",
    },
    "cap": {
        "app":     "He wore a blue cap outside.",
        "inapp":   "He wore a talking cap outside.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "hat sense forced by 'wore a blue'",
        "inapp_rat":"cap (-animate) + 'talking' (+animate)",
        "risks":   "",
    },
    "apartment": {
        "app":     "They rented a small apartment downtown.",
        "inapp":   "They rented a sleeping apartment downtown.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "place-to-live sense forced by 'rented a small'",
        "inapp_rat":"apartment (-animate) + 'sleeping' (+animate)",
        "risks":   "'sleeping apartment' faint compositional meaning (an apartment for sleeping)? Reviewer check.",
    },

    # -------- 2K VERBS --------
    "wrap": {
        "app":     "She wrapped the gift in paper.",
        "inapp":   "She wrapped the music in paper.",
        "frame":   "SVO-PP",
        "foil_sub":"b_collocation",
        "app_rat": "cover-tightly sense forced by obj 'gift' + 'in paper'",
        "inapp_rat":"wrap + direct obj 'music' non-collocate (wrap gift/box/package/present/sandwich standard)",
        "risks":   "could read as selectional (music -concrete wrap target). Reviewer flag.",
    },
    "contribute": {
        "app":     "They contributed money to the hospital.",
        "inapp":   "They contributed laughter to the hospital.",
        "frame":   "SVO-PP",
        "foil_sub":"b_collocation",
        "app_rat": "give-to sense forced by 'money to hospital'",
        "inapp_rat":"contribute + direct obj 'laughter' non-collocate (contribute money/time/effort/ideas/support standard)",
        "risks":   "spec example verbatim (§3.4 b1 variant).",
    },
    "seek": {
        "app":     "He sought advice from his father.",
        "inapp":   "He sought laughter from his father.",
        "frame":   "SVO-PP",
        "foil_sub":"b_collocation",
        "app_rat": "look-for sense forced by 'advice from father'",
        "inapp_rat":"seek + direct obj 'laughter' non-collocate (seek advice/help/approval/justice/support standard)",
        "risks":   "spec example verbatim (§3.4 b3).",
    },
    "contain": {
        "app":     "The box contains three old books.",
        "inapp":   "The box contains three loud ideas.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "have-inside sense forced by 'box' + countable obj",
        "inapp_rat":"contain + 'ideas' (+abstract) non-collocate for +physical_container subject; also 'loud ideas' unusual",
        "risks":   "FAIL-MODE-4 risk: 'loud ideas' may drive the oddness rather than contain-ideas. Flagging prominently.",
    },
    "search": {
        "app":     "She searched the room for keys.",
        "inapp":   "She searched the room for songs.",
        "frame":   "SVO-PP",
        "foil_sub":"b_collocation",
        "app_rat": "look-for sense forced by 'room for keys'",
        "inapp_rat":"search for + 'songs' in physical room non-collocate (search for keys/information/answers/clues/truth standard)",
        "risks":   "",
    },
    "avoid": {
        "app":     "She avoided heavy traffic every morning.",
        "inapp":   "She avoided heavy triangles every morning.",
        "frame":   "SVO-temporal",
        "foil_sub":"b_collocation",
        "app_rat": "try-not-to-do sense forced by 'heavy traffic' + habitual",
        "inapp_rat":"avoid + 'triangles' non-collocate (avoid traffic/conflict/mistakes/problems/eye contact standard)",
        "risks":   "",
    },
    "receive": {
        "app":     "She received a nice birthday gift.",
        "inapp":   "She received a nice birthday sky.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "get-something sense forced by 'nice birthday gift'",
        "inapp_rat":"receive + 'sky' non-collocate (receive gift/letter/email/call/message/award standard)",
        "risks":   "",
    },
    "bump": {
        "app":     "He bumped his knee on the desk.",
        "inapp":   "He bumped his dream on the desk.",
        "frame":   "SVO-PP",
        "foil_sub":"b_collocation",
        "app_rat": "hit-gently sense forced by 'knee on desk'",
        "inapp_rat":"bump + 'dream' as obj non-collocate (bump head/knee/elbow/into someone standard)",
        "risks":   "",
    },
    "include": {
        "app":     "The price includes all the drinks.",
        "inapp":   "The price includes all the whispers.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "have-as-part sense forced by 'price includes all the'",
        "inapp_rat":"include + 'whispers' non-collocate (include tax/fees/meals/drinks/breakfast standard in this price context)",
        "risks":   "",
    },
    "proud": {
        "app":     "She was proud of her daughter.",
        "inapp":   "She was proud of her pencil.",
        "frame":   "SVC-PP",
        "foil_sub":"a_selectional",
        "app_rat": "feeling-good sense forced by 'of her daughter' (+human)",
        "inapp_rat":"proud of + 'pencil' (+ordinary_object) violates +achievement/+worthwhile obj selection",
        "risks":   "",
    },
    "super": {
        "app":     "That was a super nice day.",
        "inapp":   "That was a super nice cloud.",
        "frame":   "SVC",
        "foil_sub":"b_collocation",
        "app_rat": "great sense forced by 'super' as intensifier + 'nice day'",
        "inapp_rat":"super + 'nice cloud' non-collocate; super mostly precedes evaluative contexts (nice day/job/idea/party/friend)",
        "risks":   "minority-sense. This is fragile; reviewer flag. 'super cloud' can be parsed as 'really cloudy'.",
    },
    "constant": {
        "app":     "The constant noise gave him headaches.",
        "inapp":   "The constant noise gave him triangles.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "happening-all-the-time sense forced by 'noise' + 'gave him'",
        "inapp_rat":"oddness is 'gave him triangles' rather than constant; placeholder — note foil weak",
        "risks":   "WEAK: oddness not attributable to constant. Consider revise.",
    },
    "rotten": {
        "app":     "They threw away the rotten apples.",
        "inapp":   "They threw away the rotten answers.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "bad sense forced by 'threw away' + 'apples'",
        "inapp_rat":"rotten requires +organic/+substance; 'answers' is -substance",
        "risks":   "'rotten' can be metaphorical (rotten luck). Watch idiom rescue. Reviewer flag.",
    },
    "smooth": {
        "app":     "The table had a smooth surface.",
        "inapp":   "The poem had a smooth surface.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "not-rough sense forced by 'table' (+concrete) + 'surface'",
        "inapp_rat":"'poem' is -concrete, so 'smooth surface' on a poem violates +tactile_concrete selection",
        "risks":   "marginal: 'poem has a smooth flow' is natural. Reviewer may reject; flag.",
    },
    "junior": {
        "app":     "He met the junior staff today.",
        "inapp":   "He met the junior river today.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "younger-in-position sense forced by 'staff' (+human hierarchy)",
        "inapp_rat":"junior requires +human/+hierarchical; 'river' is -human",
        "risks":   "",
    },

    # -------- 3K --------
    "behavior": {
        "app":     "His behavior changed after the meeting.",
        "inapp":   "His behavior tasted sweet today.",
        "frame":   "SVC/SV (app); SV-Adj (inapp differs — keeping frames close)",
        "foil_sub":"a_selectional",
        "app_rat": "actions sense forced by possessive + 'changed'",
        "inapp_rat":"behavior is -substance; 'tasted' requires +substance subject",
        "risks":   "synesthesia rescue risk (spec §3.4 poverty example). Reviewer flag.",
    },
    "celebration": {
        "app":     "The celebration lasted all night long.",
        "inapp":   "The celebration melted all night long.",
        "frame":   "SV-temporal",
        "foil_sub":"a_selectional",
        "app_rat": "happy-occasion sense forced by 'lasted all night'",
        "inapp_rat":"celebration (+event -substance) + 'melted' requires +substance subject",
        "risks":   "",
    },
    "apology": {
        "app":     "Her apology sounded completely sincere.",
        "inapp":   "Her apology wore a blue coat.",
        "frame":   "SV-AdjP",
        "foil_sub":"a_selectional",
        "app_rat": "saying-sorry sense forced by 'sounded' + 'sincere'",
        "inapp_rat":"apology is +verbal_act -body; 'wore a coat' requires +body",
        "risks":   "spec §3.4 worked example. Uses canonical form.",
    },
    "phrase": {
        "app":     "He learned a useful phrase today.",
        "inapp":   "He learned a happy phrase today.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "combination-of-words sense forced by 'learned' + 'useful'",
        "inapp_rat":"phrase + 'happy' non-collocate (useful/common/new/key/famous phrase standard)",
        "risks":   "'happy phrase' can mean phrase about happiness. Reviewer flag.",
    },
    "wealth": {
        "app":     "His wealth grew over many years.",
        "inapp":   "His wealth played music over many years.",
        "frame":   "SV-PP",
        "foil_sub":"b_collocation",
        "app_rat": "much-money sense forced by 'grew over years'",
        "inapp_rat":"wealth + 'played music' non-collocate; typical: wealth grew/increased/doubled/vanished",
        "risks":   "reduces to a_selectional (wealth -animate). Flagging.",
    },
    "agriculture": {
        "app":     "Modern agriculture supports many small villages.",
        "inapp":   "Modern agriculture danced in small villages.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "farming sense forced by 'modern agriculture supports villages'",
        "inapp_rat":"agriculture (-animate abstract) + 'danced' (+animate action)",
        "risks":   "",
    },
    "regime": {
        "app":     "The regime ruled the country harshly.",
        "inapp":   "The regime laughed at the country harshly.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "government sense forced by 'ruled the country'",
        "inapp_rat":"regime in tested sense is -animate abstract; 'laughed' requires +animate sentient",
        "risks":   "metonymy rescue possible (regime = rulers). Reviewer flag.",
    },
    "volunteer": {
        "app":     "The volunteer helped many old people.",
        "inapp":   "The volunteer rusted many old people.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "person-helping-without-payment sense forced by 'helped many old people'",
        "inapp_rat":"volunteer (+human) + 'rusted' (+metal) violates material selection",
        "risks":   "oddness arguably at volunteer+rust pairing; reviewer check.",
    },
    "poverty": {
        "app":     "Extreme poverty affects many rural families.",
        "inapp":   "Extreme poverty eats many rural families.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "little-money sense forced by 'extreme poverty affects rural families'",
        "inapp_rat":"poverty + 'eats' as main verb non-collocate (poverty affects/hurts/traps/grips/causes/impacts standard)",
        "risks":   "bleeds to a (poverty abstract cannot eat). Flag.",
    },
    "heritage": {
        "app":     "We should protect our cultural heritage.",
        "inapp":   "We should protect our sleeping heritage.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "history sense forced by 'protect our cultural'",
        "inapp_rat":"heritage + 'sleeping' non-collocate (cultural/national/rich/shared heritage standard)",
        "risks":   "could slide to a_selectional. Flagging.",
    },
    "asset": {
        "app":     "His skills are a great asset here.",
        "inapp":   "His skills are a great eating asset.",
        "frame":   "SVC",
        "foil_sub":"b_collocation",
        "app_rat": "useful-thing sense forced by 'skills are a great'",
        "inapp_rat":"asset + 'eating' modifier non-collocate (great/valuable/real/huge/major asset standard)",
        "risks":   "",
    },
    "intelligence": {
        "app":     "His intelligence helped solve the problem.",
        "inapp":   "His intelligence ate dinner in silence.",
        "frame":   "SVO (app); SVO-PP (inapp, slight mismatch)",
        "foil_sub":"a_selectional",
        "app_rat": "ability-to-learn sense forced by 'helped solve the problem'",
        "inapp_rat":"intelligence (-animate abstract) + 'ate' (+animate/+agent)",
        "risks":   "frame mismatch. Consider revise; but matches ±1 word constraint.",
    },
    "pit": {
        "app":     "They dug a deep pit quickly.",
        "inapp":   "They dug a talking pit quickly.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "deep-place sense forced by 'dug a deep'",
        "inapp_rat":"pit (-sentient hole) + 'talking' (+sentient)",
        "risks":   "",
    },
    "audience": {
        "app":     "The audience clapped after the show.",
        "inapp":   "The audience rusted after the show.",
        "frame":   "SV-PP",
        "foil_sub":"a_selectional",
        "app_rat": "watchers/listeners sense forced by 'clapped after show'",
        "inapp_rat":"audience (+human collective) + 'rusted' (+metal) violates material",
        "risks":   "",
    },
    "specify": {
        "app":     "Please specify the exact meeting date.",
        "inapp":   "Please specify the exact meeting cloud.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "say-clearly sense forced by 'exact meeting date'",
        "inapp_rat":"specify + 'cloud' as obj non-collocate (specify date/time/amount/location/conditions/requirements standard)",
        "risks":   "CRITICAL item. Report verb with broad collocates — foil may feel arbitrary. Native flag.",
    },
    "exhibit": {
        "app":     "The museum exhibits ancient Greek art.",
        "inapp":   "The museum exhibits ancient Greek dinners.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "show-in-public sense forced by 'museum' + 'ancient Greek art'",
        "inapp_rat":"exhibit + 'dinners' non-collocate (exhibit art/paintings/sculpture/work/artifacts standard)",
        "risks":   "CRITICAL item. Reviewer flag.",
    },
    "capture": {
        "app":     "The police captured the escaped prisoner.",
        "inapp":   "The police captured the escaped sunrise.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "catch sense forced by 'police captured' + 'escaped prisoner'",
        "inapp_rat":"capture + 'sunrise' as direct obj in this sense non-collocate (capture thief/prisoner/fugitive/town/fort standard for catch sense)",
        "risks":   "minority-sense (capture moment/beauty idiom). Foil could be rescued by 'capture a sunrise (photo)' idiom. Reviewer flag.",
    },
    "proceed": {
        "app":     "They proceeded to the next room.",
        "inapp":   "They proceeded to the next song.",
        "frame":   "SV-PP",
        "foil_sub":"b_collocation",
        "app_rat": "go-on sense forced by 'to the next room' (physical movement)",
        "inapp_rat":"proceed to + 'song' non-collocate (proceed to + next step/room/area/phase/level standard)",
        "risks":   "mild — could read as b: proceed to next song (in playlist) is natural. Weak foil; reviewer flag.",
    },
    "persist": {
        "app":     "The heavy rain persisted until morning.",
        "inapp":   "The heavy rain persisted the red sky.",
        "frame":   "SV-adv (app); SVO (inapp — frame mismatch)",
        "foil_sub":"b_collocation",
        "app_rat": "continue-to-happen sense forced by 'heavy rain' + 'until morning'",
        "inapp_rat":"persist is typically intransitive; attempting obj 'sky' creates non-collocate — but grammatical issue",
        "risks":   "CRITICAL. Ungrammatical inapp. REVISING.",
    },
    "exceed": {
        "app":     "The cost exceeded our original estimate.",
        "inapp":   "The cost exceeded our original breakfast.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "goes-beyond-limit sense forced by 'cost exceeded' + 'estimate'",
        "inapp_rat":"exceed + 'breakfast' as obj non-collocate (exceed expectations/limits/budget/estimates/target standard)",
        "risks":   "",
    },
    "approximate": {
        "app":     "Please give an approximate cost today.",
        "inapp":   "Please give an approximate cousin today.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "almost-exact sense forced by 'give an' + 'cost'",
        "inapp_rat":"approximate + 'cousin' non-collocate (approximate number/cost/time/size/value/age/weight standard)",
        "risks":   "CRITICAL item. Reviewer flag.",
    },
    "prior": {
        "app":     "His prior experience helped him greatly.",
        "inapp":   "His prior breakfast helped him greatly.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "earlier sense forced by 'prior experience' + 'helped'",
        "inapp_rat":"prior + 'breakfast' non-collocate (prior experience/knowledge/notice/approval/arrangement/engagement standard)",
        "risks":   "",
    },
    "frequent": {
        "app":     "The frequent rain damaged our garden.",
        "inapp":   "The frequent dream damaged our garden.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "happening-often sense forced by 'frequent rain' + 'damaged garden'",
        "inapp_rat":"frequent + 'dream' non-collocate (frequent visitor/flyer/use/rain/stops/trips standard)",
        "risks":   "",
    },
    "consistent": {
        "app":     "Her work was consistent last year.",
        "inapp":   "Her work was consistent last triangle.",
        "frame":   "SVC",
        "foil_sub":"b_collocation",
        "app_rat": "not-changing sense forced by 'her work was' + 'last year'",
        "inapp_rat":"oddness at 'last triangle' not at consistent. Flagging.",
        "risks":   "FAIL-MODE-4. Revise.",
    },
    "mutual": {
        "app":     "Their mutual respect grew over time.",
        "inapp":   "Their mutual cupboard grew over time.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "shared sense forced by 'mutual respect' + 'grew'",
        "inapp_rat":"mutual + 'cupboard' non-collocate (mutual respect/friend/interest/agreement/understanding/benefit standard)",
        "risks":   "",
    },

    # -------- 4K --------
    "vitamin": {
        "app":     "Doctors say vitamins help your health.",
        "inapp":   "Doctors say vitamins laugh at night.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "healthy-supplement sense forced by 'doctors' + 'help your health'",
        "inapp_rat":"vitamin (-animate) + 'laugh' (+animate)",
        "risks":   "",
    },
    "cave": {
        "app":     "The bear slept inside the cave.",
        "inapp":   "The bear slept inside the happy cave.",
        "frame":   "SV-PP",
        "foil_sub":"a_selectional",
        "app_rat": "hill-opening sense forced by 'bear slept inside'",
        "inapp_rat":"cave (-animate geological) + 'happy' (+animate)",
        "risks":   "",
    },
    "soap": {
        "app":     "He washed his hands with soap.",
        "inapp":   "He washed his hands with soap music.",
        "frame":   "SVO-PP",
        "foil_sub":"b_collocation",
        "app_rat": "cleaning-product sense forced by 'washed hands with'",
        "inapp_rat":"target's modifier slot: 'soap music' is a compound that collapses foil; REVISING.",
        "risks":   "REVISE.",
    },
    "tutor": {
        "app":     "The tutor taught me some math.",
        "inapp":   "The tutor taught me some clouds.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "teacher sense forced by 'taught me'",
        "inapp_rat":"tutor taught + 'clouds' as subj matter non-collocate (math/English/grammar/piano/chess/history standard)",
        "risks":   "swap is at verb arg, not direct modifier of tutor. Flag.",
    },
    "diamond": {
        "app":     "She wore a small diamond ring.",
        "inapp":   "She wore a small diamond cloud.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "valuable-stone sense forced by 'wore a small' + 'ring'",
        "inapp_rat":"the swapped word 'cloud' is the head noun not direct mod of diamond. Revising.",
        "risks":   "REVISE.",
    },
    "orchestra": {
        "app":     "The orchestra played classical music beautifully.",
        "inapp":   "The orchestra ate classical music beautifully.",
        "frame":   "SVO-adv",
        "foil_sub":"a_selectional",
        "app_rat": "music-group sense forced by 'played classical music'",
        "inapp_rat":"orchestra (+human collective) with 'ate classical music' — eat+music invalid; but oddness at eat-music",
        "risks":   "FAIL-MODE-4. Revise.",
    },
    "slot": {
        "app":     "He put a coin in the slot.",
        "inapp":   "He put a dream in the slot.",
        "frame":   "SVO-PP",
        "foil_sub":"a_selectional",
        "app_rat": "thin-opening sense forced by 'put a coin in'",
        "inapp_rat":"the oddness comes from 'put a dream in the slot' — not slot's direct selection. Fail-mode-4.",
        "risks":   "Revise.",
    },
    "scrap": {
        "app":     "She found a scrap of paper.",
        "inapp":   "She found a scrap of smile.",
        "frame":   "SVO-PP",
        "foil_sub":"a_selectional",
        "app_rat": "small-unwanted-piece sense forced by 'found a scrap of paper'",
        "inapp_rat":"scrap of + 'smile' non-collocate / selectional (scrap of + paper/cloth/food/metal/wood standard; +substance required)",
        "risks":   "could go either a or b.",
    },
    "crust": {
        "app":     "The bread had a hard crust.",
        "inapp":   "The bread had a quick crust.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "hard-outside-part sense forced by 'bread had a hard'",
        "inapp_rat":"crust + 'quick' non-collocate (hard/thick/crispy/golden/bread crust standard)",
        "risks":   "",
    },
    "verdict": {
        "app":     "The jury gave a fair verdict.",
        "inapp":   "The jury gave a sleepy verdict.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "judgment sense forced by 'jury gave a fair'",
        "inapp_rat":"verdict + 'sleepy' non-collocate (fair/unanimous/guilty/final verdict standard)",
        "risks":   "",
    },
    "venue": {
        "app":     "The venue was near the river.",
        "inapp":   "The venue was near the triangle.",
        "frame":   "SVC-PP",
        "foil_sub":"b_collocation",
        "app_rat": "place sense forced by copula + 'near the river'",
        "inapp_rat":"oddness 'near the triangle' not tied to venue directly. Flag.",
        "risks":   "FAIL-MODE-4. Revise.",
    },
    "embassy": {
        "app":     "The embassy stands on a busy road.",
        "inapp":   "The embassy eats on a busy road.",
        "frame":   "SV-PP",
        "foil_sub":"a_selectional",
        "app_rat": "government-building sense forced by 'stands on busy road'",
        "inapp_rat":"embassy (-animate building) + 'eats' (+animate)",
        "risks":   "",
    },
    "tobacco": {
        "app":     "Farmers here grow tobacco every summer.",
        "inapp":   "Farmers here grow angry tobacco every summer.",
        "frame":   "SVO-temporal",
        "foil_sub":"a_selectional",
        "app_rat": "smoking-plant sense forced by 'farmers grow'",
        "inapp_rat":"tobacco (-sentient plant) + 'angry' (+sentient)",
        "risks":   "",
    },
    "alley": {
        "app":     "They walked down the dark alley.",
        "inapp":   "They walked down the talking alley.",
        "frame":   "SV-PP",
        "foil_sub":"a_selectional",
        "app_rat": "small-street sense forced by 'walked down'",
        "inapp_rat":"alley (-animate) + 'talking' (+animate)",
        "risks":   "",
    },
    "forbid": {
        "app":     "Teachers forbid phones in the classroom.",
        "inapp":   "Teachers forbid clouds in the classroom.",
        "frame":   "SVO-PP",
        "foil_sub":"b_collocation",
        "app_rat": "not-allow sense forced by 'phones in classroom'",
        "inapp_rat":"forbid + 'clouds' non-collocate in this context (forbid smoking/phones/weapons/running/entry standard)",
        "risks":   "oddness partly at 'clouds in classroom'. Flag.",
    },
    "shrink": {
        "app":     "The shirt shrank in hot water.",
        "inapp":   "The shirt shrank in happy water.",
        "frame":   "SV-PP",
        "foil_sub":"b_collocation",
        "app_rat": "make-smaller sense forced by 'shirt shrank in hot water'",
        "inapp_rat":"'happy water' modifier pair — oddness between happy-water, not shrink-water. Flag.",
        "risks":   "FAIL-MODE-4. Revise.",
    },
    "fling": {
        "app":     "He will fling the ball into the yard.",
        "inapp":   "He will fling the song into the yard.",
        "frame":   "SVO-PP",
        "foil_sub":"b_collocation",
        "app_rat": "throw sense forced by 'ball into yard'",
        "inapp_rat":"fling + 'song' as direct obj non-collocate; fling ball/stone/door/bag/hat standard (+physical_object required by direct obj collocation)",
        "risks":   "bleeds into selectional (song -physical). Flag.",
    },
    "weep": {
        "app":     "The old men often weep at dawn.",
        "inapp":   "The old tables often weep at dawn.",
        "frame":   "SV-PP",
        "foil_sub":"b_collocation",
        "app_rat": "cry sense forced by '+human subjects weep at dawn'",
        "inapp_rat":"weep's subject 'tables' is non-collocate (weep requires +animate/+sentient)",
        "risks":   "could be labeled a. Flag.",
    },
    "disclose": {
        "app":     "She disclosed the news very quickly.",
        "inapp":   "She disclosed the tree very quickly.",
        "frame":   "SVO-adv",
        "foil_sub":"b_collocation",
        "app_rat": "tell sense forced by 'news' + 'quickly'",
        "inapp_rat":"disclose + 'tree' non-collocate (disclose information/details/news/identity/facts/secrets standard)",
        "risks":   "",
    },
    "activate": {
        "app":     "Press the button to activate the alarm.",
        "inapp":   "Press the button to activate the cloud.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "turn-on sense forced by 'press button to activate alarm'",
        "inapp_rat":"activate + 'cloud' non-collocate (activate alarm/account/system/device/feature standard)",
        "risks":   "",
    },
    "explode": {
        "app":     "The bomb exploded near the house.",
        "inapp":   "The bomb exploded near the breakfast.",
        "frame":   "SV-PP",
        "foil_sub":"b_collocation",
        "app_rat": "break-into-pieces sense forced by 'bomb exploded near house'",
        "inapp_rat":"oddness at 'near breakfast' location, not tied to explode. Flag.",
        "risks":   "FAIL-MODE-4. Revise.",
    },
    "diminish": {
        "app":     "His wealth diminished over ten years.",
        "inapp":   "His wealth diminished over ten breakfasts.",
        "frame":   "SV-PP",
        "foil_sub":"b_collocation",
        "app_rat": "get-smaller sense forced by 'wealth' + 'over ten years'",
        "inapp_rat":"oddness at 'over ten breakfasts' — unit not diminish-specific. Flag.",
        "risks":   "FAIL-MODE-4. Revise.",
    },
    "transplant": {
        "app":     "Doctors transplanted the heart on Tuesday.",
        "inapp":   "Doctors transplanted the story on Tuesday.",
        "frame":   "SVO-temporal",
        "foil_sub":"b_collocation",
        "app_rat": "move-to-another-place sense forced by 'doctors' + 'heart'",
        "inapp_rat":"transplant + 'story' non-collocate (transplant heart/kidney/liver/organ/tree standard)",
        "risks":   "",
    },
    "adjacent": {
        "app":     "The shop is adjacent to the bank.",
        "inapp":   "The shop is adjacent to the dream.",
        "frame":   "SVC-PP",
        "foil_sub":"b_collocation",
        "app_rat": "beside sense forced by 'shop is adjacent to bank' (+physical)",
        "inapp_rat":"adjacent to + 'dream' (-physical) non-collocate; adjacent to + physical location standard",
        "risks":   "bleeds into selectional. Flag.",
    },
    "sane": {
        "app":     "The doctor said he was sane.",
        "inapp":   "The rock said he was sane.",
        "frame":   "SVO-complement",
        "foil_sub":"a_selectional",
        "app_rat": "not-crazy sense forced by +human subj 'doctor' + 'said'",
        "inapp_rat":"subject 'rock' -animate + 'said' requires +animate. Violation distant from target.",
        "risks":   "FAIL-MODE-4. Revise.",
    },
    "swift": {
        "app":     "The swift horse won the race.",
        "inapp":   "The swift idea won the race.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "quick sense forced by 'swift horse' + 'won race'",
        "inapp_rat":"swift + 'idea' non-collocate (swift reply/action/response/movement/horse/river standard)",
        "risks":   "bleeds to selectional (idea can't win race). Flag.",
    },
    "credible": {
        "app":     "His story seemed credible at first.",
        "inapp":   "His pizza seemed credible at first.",
        "frame":   "SVC",
        "foil_sub":"a_selectional",
        "app_rat": "believable sense forced by 'story' (+proposition) + 'seemed'",
        "inapp_rat":"'pizza' (+food) + 'credible' is oddness of modifier-head pair, but pizza can't be credible",
        "risks":   "could be mod-N selectional. Flag.",
    },
    "greasy": {
        "app":     "The greasy food made her sick.",
        "inapp":   "The greasy sound made her sick.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "oily sense forced by 'food' + 'made her sick'",
        "inapp_rat":"greasy requires +substance/+tactile; 'sound' is -substance",
        "risks":   "synesthesia rescue risk. Flag.",
    },
    "abnormal": {
        "app":     "The abnormal test result surprised her.",
        "inapp":   "The abnormal sunset surprised her.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "unusual sense forced by 'test result' medical context",
        "inapp_rat":"abnormal + 'sunset' non-collocate (abnormal behavior/result/growth/level/cell/reading standard)",
        "risks":   "",
    },

    # -------- 5K --------
    "mustache": {
        "app":     "His mustache was long and black.",
        "inapp":   "His mustache was long and angry.",
        "frame":   "SVC",
        "foil_sub":"a_selectional",
        "app_rat": "upper-lip-hair sense forced by 'long and black'",
        "inapp_rat":"mustache (-animate body part) + 'angry' (+sentient) violates animacy of predicate",
        "risks":   "",
    },
    "paradise": {
        "app":     "This island feels like a paradise.",
        "inapp":   "This island feels like a sleeping paradise.",
        "frame":   "SVC",
        "foil_sub":"a_selectional",
        "app_rat": "perfect-place sense forced by 'island feels like'",
        "inapp_rat":"paradise (+place) + 'sleeping' (+animate) violates animacy",
        "risks":   "",
    },
    "pastry": {
        "app":     "She baked a sweet pastry today.",
        "inapp":   "She baked a loud pastry today.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "baked-food sense forced by 'baked a sweet'",
        "inapp_rat":"pastry (-audible) + 'loud' (+audible required)",
        "risks":   "",
    },
    "vase": {
        "app":     "She put flowers in the vase.",
        "inapp":   "She put flowers in the loud vase.",
        "frame":   "SVO-PP",
        "foil_sub":"b_collocation",
        "app_rat": "flower-container sense forced by 'put flowers in'",
        "inapp_rat":"vase + 'loud' non-collocate (tall/small/crystal/glass/empty/broken vase standard)",
        "risks":   "could slide to a. Flag.",
    },
    "chord": {
        "app":     "She played a beautiful chord softly.",
        "inapp":   "She played a talking chord softly.",
        "frame":   "SVO-adv",
        "foil_sub":"b_collocation",
        "app_rat": "musical-notes sense forced by 'played a beautiful'",
        "inapp_rat":"chord + 'talking' non-collocate (beautiful/major/minor/final/opening/sad chord standard)",
        "risks":   "bleeds to a. Flag.",
    },
    "rectangle": {
        "app":     "She drew a large rectangle carefully.",
        "inapp":   "She drew a talking rectangle carefully.",
        "frame":   "SVO-adv",
        "foil_sub":"b_collocation",
        "app_rat": "shape sense forced by 'drew a large'",
        "inapp_rat":"rectangle + 'talking' non-collocate (large/small/long/thin/perfect/blue rectangle standard)",
        "risks":   "bleeds to a. Flag.",
    },
    "lime": {
        "app":     "He squeezed a fresh green lime.",
        "inapp":   "He squeezed a fresh talking lime.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "green-fruit sense forced by 'squeezed a fresh green'",
        "inapp_rat":"lime (-animate fruit) + 'talking' (+animate)",
        "risks":   "",
    },
    "hum": {
        "app":     "The hum of the engine stopped.",
        "inapp":   "The hum of the engine cried.",
        "frame":   "SV",
        "foil_sub":"a_selectional",
        "app_rat": "low-constant-sound sense forced by 'hum of the engine'",
        "inapp_rat":"hum (-animate sound) + 'cried' (+animate)",
        "risks":   "",
    },
    "pork": {
        "app":     "They cooked pork for the party.",
        "inapp":   "They cooked talking pork for the party.",
        "frame":   "SVO-PP",
        "foil_sub":"a_selectional",
        "app_rat": "pig-meat sense forced by 'cooked pork for party'",
        "inapp_rat":"pork (-animate meat) + 'talking' (+animate)",
        "risks":   "",
    },
    "perfume": {
        "app":     "She wore a sweet perfume tonight.",
        "inapp":   "She wore a loud perfume tonight.",
        "frame":   "SVO-temporal",
        "foil_sub":"b_collocation",
        "app_rat": "nice-smelling-liquid sense forced by 'wore a sweet'",
        "inapp_rat":"perfume + 'loud' non-collocate (sweet/strong/expensive/French/heavy/light perfume standard)",
        "risks":   "bleeds to a. Flag.",
    },
    "wizard": {
        "app":     "The wizard cast a simple spell.",
        "inapp":   "The wizard cast a delicious spell.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "magic-user sense forced by 'wizard cast' + 'spell'",
        "inapp_rat":"oddness at 'delicious spell' rather than wizard+<obj>. Flag.",
        "risks":   "FAIL-MODE-4. Revise.",
    },
    "sanctuary": {
        "app":     "This small church feels like a sanctuary.",
        "inapp":   "This small church feels like a loud sanctuary.",
        "frame":   "SVC",
        "foil_sub":"b_collocation",
        "app_rat": "safe-place sense forced by 'church feels like'",
        "inapp_rat":"sanctuary + 'loud' non-collocate (safe/quiet/peaceful/bird/wildlife sanctuary standard)",
        "risks":   "bleeds to a (sanctuary = quiet by definition). Good foil because conflicts with core meaning.",
    },
    "altitude": {
        "app":     "The plane reached a very high altitude.",
        "inapp":   "The plane reached a very happy altitude.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "height sense forced by 'plane reached a very high'",
        "inapp_rat":"altitude (-sentient measure) + 'happy' (+sentient)",
        "risks":   "",
    },
    "robe": {
        "app":     "She wore a long white robe.",
        "inapp":   "She wore a long talking robe.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "clothing sense forced by 'wore a long white'",
        "inapp_rat":"robe (-animate clothing) + 'talking' (+animate)",
        "risks":   "",
    },
    "pirate": {
        "app":     "The pirate attacked the small ship.",
        "inapp":   "The pirate melted the small ship.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "ship-attacker sense forced by 'pirate attacked' + 'ship'",
        "inapp_rat":"oddness at pirate+melted; pirate (+animate) + 'melted' (+substance process) violates agent selection",
        "risks":   "",
    },

    # 5K verbs
    "notify": {
        "app":     "Please notify the staff about this change.",
        "inapp":   "Please notify the staff about this sunset.",
        "frame":   "SVO-PP",
        "foil_sub":"b_collocation",
        "app_rat": "announce sense forced by 'notify the staff about this change'",
        "inapp_rat":"notify about + 'sunset' non-collocate (notify about change/decision/meeting/delay/problem standard)",
        "risks":   "",
    },
    "intrude": {
        "app":     "He intruded into their private meeting.",
        "inapp":   "He intruded into their private cookie.",
        "frame":   "SV-PP",
        "foil_sub":"b_collocation",
        "app_rat": "enter-without-permission sense forced by 'intruded into' + 'private meeting'",
        "inapp_rat":"intrude into + 'cookie' non-collocate (intrude into privacy/meeting/life/conversation/space standard)",
        "risks":   "bleeds to a (cookie -enterable). Flag.",
    },
    "erase": {
        "app":     "She erased the old notes carefully.",
        "inapp":   "She erased the old storms carefully.",
        "frame":   "SVO-adv",
        "foil_sub":"b_collocation",
        "app_rat": "remove sense forced by 'erased the old notes'",
        "inapp_rat":"erase + 'storms' non-collocate (erase notes/memories/data/mark/name/board standard)",
        "risks":   "",
    },
    "shred": {
        "app":     "He shredded the old papers quickly.",
        "inapp":   "He shredded the old dreams quickly.",
        "frame":   "SVO-adv",
        "foil_sub":"b_collocation",
        "app_rat": "tear-into-pieces sense forced by 'shredded the old papers'",
        "inapp_rat":"shred + 'dreams' non-collocate in physical sense (shred paper/document/cheese/cabbage standard)",
        "risks":   "bleeds to a/metaphor (shred dreams idiom). Flag.",
    },
    "expire": {
        "app":     "Her visa expired last month already.",
        "inapp":   "Her song expired last month already.",
        "frame":   "SV-temporal",
        "foil_sub":"b_collocation",
        "app_rat": "end sense forced by 'visa expired last month'",
        "inapp_rat":"expire + subject 'song' non-collocate (visa/contract/passport/license/membership/food expires standard)",
        "risks":   "could be labeled a (song -temporal-limited). Flag.",
    },
    "meditate": {
        "app":     "She meditates for ten quiet minutes.",
        "inapp":   "She meditates for ten quiet potatoes.",
        "frame":   "SV-PP",
        "foil_sub":"b_collocation",
        "app_rat": "think-deeply sense forced by 'for ten quiet minutes'",
        "inapp_rat":"oddness at 'ten quiet potatoes' duration unit, not tied to meditate. Flag.",
        "risks":   "FAIL-MODE-4. Revise.",
    },
    "ignite": {
        "app":     "The small spark ignited the dry grass.",
        "inapp":   "The small spark ignited the loud grass.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "catch-fire sense forced by 'spark ignited dry grass'",
        "inapp_rat":"oddness at 'loud grass' pair, not tied to ignite. Flag.",
        "risks":   "FAIL-MODE-4. Revise.",
    },
    "swap": {
        "app":     "They swapped seats during the movie.",
        "inapp":   "They swapped clouds during the movie.",
        "frame":   "SVO-PP",
        "foil_sub":"b_collocation",
        "app_rat": "exchange sense forced by 'swapped seats during movie'",
        "inapp_rat":"swap + direct obj 'clouds' non-collocate (swap seats/places/stories/numbers/gifts/jobs standard)",
        "risks":   "",
    },
    "pierce": {
        "app":     "The sharp nail pierced his old shoe.",
        "inapp":   "The sharp nail pierced his old song.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "go-through sense forced by 'sharp nail pierced his old shoe'",
        "inapp_rat":"pierce + 'song' (-physical) non-collocate (pierce skin/ear/hole/heart/shoe standard)",
        "risks":   "bleeds to a. Flag.",
    },

    # 5K adjectives
    "tranquil": {
        "app":     "The tranquil lake glowed in moonlight.",
        "inapp":   "The tranquil argument glowed in moonlight.",
        "frame":   "SV-PP",
        "foil_sub":"a_selectional",
        "app_rat": "calm-and-quiet sense forced by 'lake' + 'glowed'",
        "inapp_rat":"tranquil requires +peaceful_entity/+place; 'argument' is +conflict, contradicts core meaning",
        "risks":   "oddness lies in argument-glowed pair too. Flag.",
    },
    "bald": {
        "app":     "The bald man smiled at us.",
        "inapp":   "The bald idea smiled at us.",
        "frame":   "SV-PP",
        "foil_sub":"a_selectional",
        "app_rat": "no-hair sense forced by +human subj + 'smiled'",
        "inapp_rat":"bald requires +can_have_hair (body surface); 'idea' is -physical",
        "risks":   "idiom risk: 'bald statement/claim' is natural. Reviewer flag.",
    },
    "moist": {
        "app":     "The moist cake tasted very good.",
        "inapp":   "The moist idea tasted very good.",
        "frame":   "SVC",
        "foil_sub":"a_selectional",
        "app_rat": "slightly-wet sense forced by 'cake' + 'tasted'",
        "inapp_rat":"moist requires +substance; 'idea' -substance",
        "risks":   "",
    },
    "tame": {
        "app":     "The tame rabbit came closer slowly.",
        "inapp":   "The tame idea came closer slowly.",
        "frame":   "SV-adv",
        "foil_sub":"a_selectional",
        "app_rat": "not-dangerous sense forced by 'rabbit' + 'came closer'",
        "inapp_rat":"tame requires +animal capable of being wild; 'idea' -animal",
        "risks":   "idiom risk: 'tame idea/version' is natural (=boring). Flag.",
    },
    "prudent": {
        "app":     "His prudent choice saved the family.",
        "inapp":   "His prudent carrot saved the family.",
        "frame":   "SVO",
        "foil_sub":"a_selectional",
        "app_rat": "using-good-judgment sense forced by 'choice saved the family'",
        "inapp_rat":"prudent requires +agent/+decision; 'carrot' -agent",
        "risks":   "",
    },
}


# =============================================================================
# Revisions for weak initial drafts (fail-mode-4 or other issues):
# These replace the placeholders above with better-matched pairs.
# =============================================================================
REVISIONS: dict[str, dict[str, str]] = {
    "coach": {
        "app":     "The coach praised every young player today.",
        "inapp":   "The coach swallowed every young player today.",
        "frame":   "SVO-temporal",
        "foil_sub":"a_selectional",
        "app_rat": "trainer sense forced by 'coach praised every young player'",
        "inapp_rat":"coach (+human trainer) + 'swallowed' (+ingestion) violates the agent-action compatibility; coaches praise/train/teach/encourage/criticize players",
        "risks":   "iteration 2 — human subject retained, violation relocated onto main verb.",
    },
    "constant": {
        "app":     "The constant noise bothered her friends.",
        "inapp":   "The constant friend bothered her breakfast.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "happening-all-the-time sense forced by 'constant noise bothered'",
        "inapp_rat":"constant + 'friend' unusual in tested sense (constant noise/pain/pressure/reminder/fear/change standard)",
        "risks":   "bleed: 'constant friend' can mean loyal friend. Reviewer flag.",
    },
    "consistent": {
        "app":     "Her grades have been consistent recently.",
        "inapp":   "Her grades have been consistent apples.",
        "frame":   "SVC",
        "foil_sub":"b_collocation",
        "app_rat": "not-changing sense forced by 'grades have been consistent'",
        "inapp_rat":"consistent + 'apples' non-collocate; consistent quality/results/performance/approach/message standard",
        "risks":   "grammatical oddness: copula+pl N needs article. Iteration 3.",
    },
    "persist": {
        "app":     "The heavy rain persisted for three days.",
        "inapp":   "The heavy rain persisted for three triangles.",
        "frame":   "SV-PP",
        "foil_sub":"b_collocation",
        "app_rat": "continue-to-happen sense forced by 'heavy rain persisted for three days'",
        "inapp_rat":"persisted for + 'triangles' non-collocate duration unit (hours/days/weeks/months/years standard)",
        "risks":   "CRITICAL item. FAIL-MODE-4 risk: oddness at for+triangles, not persist. Reviewer flag.",
    },
    "soap": {
        "app":     "He washed his hands with soap carefully.",
        "inapp":   "He washed his hands with angry soap.",
        "frame":   "SVO-PP",
        "foil_sub":"b_collocation",
        "app_rat": "cleaning-product sense forced by 'washed hands with'",
        "inapp_rat":"soap + 'angry' non-collocate (bar/liquid/hand/dish/fresh soap standard)",
        "risks":   "bleeds to a. Flag.",
    },
    "diamond": {
        "app":     "She wore a small diamond ring.",
        "inapp":   "She wore a sleeping diamond ring.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "valuable-stone sense forced by 'wore a small' + 'ring'",
        "inapp_rat":"diamond + 'sleeping' mod non-collocate (small/large/fake/real/engagement/tiny diamond standard)",
        "risks":   "bleeds to a. Flag.",
    },
    "orchestra": {
        "app":     "The orchestra played the symphony beautifully.",
        "inapp":   "The orchestra ate the symphony beautifully.",
        "frame":   "SVO-adv",
        "foil_sub":"a_selectional",
        "app_rat": "music-group sense forced by 'played the symphony'",
        "inapp_rat":"orchestra (+collective playing entity) with 'ate' violates activity selection; typical: play/perform/rehearse music",
        "risks":   "could be b_collocation. Per input type 'a'.",
    },
    "slot": {
        "app":     "He dropped a coin into the slot.",
        "inapp":   "He dropped a coin into the loud slot.",
        "frame":   "SVO-PP",
        "foil_sub":"a_selectional",
        "app_rat": "thin-opening sense forced by 'coin into'",
        "inapp_rat":"slot (-audible opening) + 'loud' (+audible)",
        "risks":   "",
    },
    "venue": {
        "app":     "The venue had a beautiful garden.",
        "inapp":   "The venue had a beautiful appetite.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "place sense forced by 'venue had a beautiful garden' (physical features)",
        "inapp_rat":"venue + obj 'appetite' non-collocate; venue has + location/feature/atmosphere/seating standard",
        "risks":   "",
    },
    "shrink": {
        "app":     "The cotton shirt will shrink in water.",
        "inapp":   "The cotton shirt will shrink in silence.",
        "frame":   "SV-PP",
        "foil_sub":"b_collocation",
        "app_rat": "make-smaller sense forced by 'cotton shirt will shrink in water'",
        "inapp_rat":"shrink in + 'silence' non-collocate (shrink in water/heat/wash/size standard)",
        "risks":   "bleeds to a. Flag.",
    },
    "explode": {
        "app":     "The bomb exploded in the old car.",
        "inapp":   "The bomb exploded in the loud song.",
        "frame":   "SV-PP",
        "foil_sub":"b_collocation",
        "app_rat": "break-into-pieces sense forced by 'bomb exploded in the old car'",
        "inapp_rat":"explode in + 'song' non-collocate; explode in + location standard",
        "risks":   "bleeds to a. Flag.",
    },
    "diminish": {
        "app":     "His energy diminished after the long walk.",
        "inapp":   "His energy diminished after the long bread.",
        "frame":   "SV-PP",
        "foil_sub":"b_collocation",
        "app_rat": "get-smaller sense forced by 'energy diminished after long walk'",
        "inapp_rat":"diminished after + 'bread' non-collocate duration/event",
        "risks":   "FAIL-MODE-4 redux. Flag.",
    },
    "sane": {
        "app":     "The doctor said he was sane.",
        "inapp":   "The doctor said he was sane bread.",
        "frame":   "SVO-complement",
        "foil_sub":"a_selectional",
        "app_rat": "not-crazy sense forced by 'doctor said he was'",
        "inapp_rat":"sane + 'bread' — sane requires +mind_capable; 'bread' -mind",
        "risks":   "ungrammatical coordination. Revise.",
    },
    "wizard": {
        "app":     "The wizard cast a long spell.",
        "inapp":   "The wizard cast a sleeping spell carefully.",
        "frame":   "SVO (app); SVO-adv (inapp 8 words)",
        "foil_sub":"b_collocation",
        "app_rat": "magic-user sense forced by 'wizard cast a spell'",
        "inapp_rat":"wizard + 'sleeping' mod; typical: wizard casts/performs/uses spell — sleeping modifier nonstandard",
        "risks":   "FAIL-MODE-4 risk remains at spell-modifier. Flag.",
    },
    "meditate": {
        "app":     "She meditated quietly in her room.",
        "inapp":   "She meditated loudly in her room.",
        "frame":   "SV-adv-PP",
        "foil_sub":"b_collocation",
        "app_rat": "think-deeply sense forced by 'quietly in her room'",
        "inapp_rat":"meditate + 'loudly' non-collocate (meditate quietly/silently/deeply/alone/daily standard)",
        "risks":   "bleeds to a (meditate -loud-compatible). Flag.",
    },
    "ignite": {
        "app":     "The spark ignited the old newspaper.",
        "inapp":   "The spark ignited the old dream.",
        "frame":   "SVO",
        "foil_sub":"b_collocation",
        "app_rat": "catch-fire sense forced by 'spark ignited old newspaper'",
        "inapp_rat":"ignite + direct obj 'dream' in literal sense non-collocate (ignite paper/fire/gas/fuel/wood standard)",
        "risks":   "metaphor rescue: 'ignite a dream' idiom. Flag.",
    },
    "bald": {
        "app":     "The bald man waved at us.",
        "inapp":   "The bald rainbow waved at us.",
        "frame":   "SV-PP",
        "foil_sub":"a_selectional",
        "app_rat": "no-hair sense forced by +human subj 'man' + 'waved'",
        "inapp_rat":"bald requires +hair-capable body surface; 'rainbow' -physical-body",
        "risks":   "",
    },
    "tame": {
        "app":     "The tame fox came closer quietly.",
        "inapp":   "The tame number came closer quietly.",
        "frame":   "SV-adv",
        "foil_sub":"a_selectional",
        "app_rat": "not-dangerous sense forced by 'fox came closer'",
        "inapp_rat":"tame requires +animal; 'number' -animal",
        "risks":   "",
    },
}

# Apply revisions
for key, val in REVISIONS.items():
    SENTENCES[key] = val


# =============================================================================
# Read Q-matrix and write draft CSV
# =============================================================================
def main() -> None:
    with Q_MATRIX.open(encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    output_rows: list[dict] = []
    missing: list[str] = []

    for r in rows:
        t = r["target_word"]
        cond = r["condition"]
        spec = SENTENCES.get(t)
        if spec is None:
            missing.append(t)
            sentence = ""
            frame = ""
            foil_sub = ""
            rationale = "MISSING"
            risks = "no template"
        else:
            sentence = spec["app"] if cond == "appropriate" else spec["inapp"]
            frame = spec.get("frame", "")
            foil_sub = spec.get("foil_sub", "") if cond == "inappropriate" else ""
            rationale = spec.get("app_rat", "") if cond == "appropriate" else spec.get("inapp_rat", "")
            risks = spec.get("risks", "")

        output_rows.append({
            "item_id": r["item_id"],
            "target_word": t,
            "target_level": r["target_level"],
            "target_POS": r["target_POS"],
            "tested_sense_desc": r["tested_sense_desc"],
            "condition": cond,
            "foil_type": r["foil_type"],
            "foil_subtype": foil_sub,
            "review_priority": r["review_priority"],
            "ljt_eligibility": r["ljt_eligibility"],
            "sentence_text": sentence,
            "syntactic_frame": frame,
            "rationale": rationale,
            "known_risks": risks,
            "llm_draft_version": LLM_VERSION,
        })

    cols = [
        "item_id","target_word","target_level","target_POS","tested_sense_desc",
        "condition","foil_type","foil_subtype","review_priority","ljt_eligibility",
        "sentence_text","syntactic_frame","rationale","known_risks","llm_draft_version",
    ]

    with OUTPUT.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=cols)
        writer.writeheader()
        for row in output_rows:
            writer.writerow(row)

    print(f"Wrote {len(output_rows)} rows to {OUTPUT}")
    if missing:
        print(f"MISSING templates for targets: {sorted(set(missing))}")


if __name__ == "__main__":
    main()
